;METADATA=(Diff=true, UseCommands=true)
[/Script/Dominion.DedicatedServerSettings]
OwnerId={{OwnerID}}
ServerName={{ServerName}}
WorldPassword={{WorldPassword}}
DefaultWorldName={{DefaultWorldName}}
AdminPassword={{AdminPassword}}
